### PR TITLE
Add `query_counter` and `get_query_parameter_u64_with_offset`

### PR DESCRIPTION
**Pull request by Zoxc**
Not sure about the naming of `get_query_parameter_ptr`, as `ptr` doesn't correspond to `u32` in `get_query_parameter_u32`.

### CODE REVIEW

**Comment by grovesNL** [comment]
Thanks! I'm not sure about the `value: *mut ()` here - could we return the value directly instead?

**Comment by Zoxc** [comment]
It's an input, so that won't work. Maybe name it `get_query_parameter_with_offset` which takes `usize`?

**Comment by grovesNL** [comment]
Oh I see, yeah `get_query_parameter_with_offset` with `usize` sounds good!

**Comment by Zoxc** [comment]
I've changed this to use the 64-bit variant and renamed the function to `get_query_parameter_u64_with_offset`.

**Review by grovesNL — APPROVED** [review]
Thank you!

**Pull request merged**
