### PR TITLE
Add compressed_tex_image_(1/2/3)d

### PR DESCRIPTION
**Pull request by mrDIMAS**

### CODE REVIEW

**Comment by TannerRogalsky** [comment]
There are a number of WebGL extensions for compressed textures. Would you consider adding support for them in this PR? I think it would amount to rewriting the internal format to the value provided by the extension when available.

**Comment by mrDIMAS** [comment]
How do you mean? Everything related to compressed textures differs only by internal format, for example BCn, ASTC, etc. Interface remains the same, so I think it should work fine as it is (and it does in my case in rg3d game engine).

**Comment by TannerRogalsky** [comment]
What I mean is that, on web platforms, the internal format must be remapped to the one provided by the appropriate extension.

For example. `glow::ETC1_RGB8_OES` would become `web_sys::WebglCompressedTextureEtc1::COMPRESSED_RGB_ETC1_WEBGL`.

I believe that it's correct that this should happen in the `compressed_tex_image_*d` function. It mirrors our existing way of expanding functionality when extensions provide it and wouldn't require changes to the way consts are exposed.

**Comment by grovesNL** [comment]
Thanks for the PR @mrDIMAS!

Are the values for any of the compressed textures internal formats different between OpenGL/OpenGL ES/WebGL? For `ETC1_RGB8_OES`, I think 0x8D64 is used for both `GL_ETC1_RGB8_OES` and `COMPRESSED_RGB_ETC1_WEBGL` so it probably wouldn't need to be remapped, but maybe others are different. Either way we could probably proceed with this as-is and internally remap later if it would be useful somewhere.

**Review by grovesNL — APPROVED** [review]
bors r+

**Pull request merged**
