### PR TITLE
Use newtypes for native GL handles

### LINKED ISSUE #178: Use NonZeroU32 for all handles
This will enforce the semantic of `Option<Handle>`, which is used quite a bit, and also reduce the data passed in registers to these function calls.

### PR DESCRIPTION
**Pull request by grovesNL**
Fixes #178 and should help https://github.com/grovesNL/glow/issues/76#issuecomment-872806982

### CODE REVIEW

**Comment by grovesNL** [comment]
@kvark @rspencer01 would you like to review?

**Review by kvark — APPROVED** [review]
This is great, thank you!

**Comment by rspencer01** [comment]
That was fast! Was planning to get round to it this afternoon!

Looks good, catches my (silly) error at compile time.  Very happy.

**Comment by grovesNL** [comment]
Great :) thanks for the reviews!
bors r=kvark,rspencer01

**Pull request merged**
