### PR TITLE
Update 'hello' example to use glutin v0.31 and winit v0.29 

### PR DESCRIPTION
**Pull request by dmbfm**
Related to issue https://github.com/grovesNL/glow/issues/249.

Since glutin no longer bundles winit, we need a lot of additional dependencies now: winit, glutin-winit and raw-window-handle. I grouped them in a feature named `glutin_winit`.

 The boilerplate to configure the window is a lot longer as well. I am not 100% sure I configured everything correctly, but I mostly stuck with the example code in the glutin repo.

### CODE REVIEW

**Comment by grovesNL** [comment]
You can bump the pinned Rust version to 1.64 to get that last build working -- I think the two places are the README and the CI configuration

**Comment by dmbfm** [comment]
Thanks, I'll do that!

**Comment by dmbfm** [comment]
@grovesNL It seems we need 1.65... is that ok?

**Comment by grovesNL** [comment]
Sure, let's bump it to 1.65

**Review by grovesNL — APPROVED** [review]
Nice, thank you! The window/context setup code all seems reasonable to me

**Pull request merged**
